### ISSUE TITLE
Support for UpdateChanStatus

### ISSUE THREAD

**Issue by BhaagBoseDK** [accumulator/charge-lnd#44] opened 2021-08-24 13:48 UTC
It would be great to have support for [updatechanstatus](https://api.lightning.community/#v2-router-updatechanstatus)

so to stop routing status can be set to Disable
to allow routing the status can be set to Enable.

This can be used with liquidity setting for example max.chan_ratio = 0.1, disbale channel.

Most people today use workaround to raise fees instead which has other issues.

**Comment by accumulator** [comment] 2021-08-28 07:29
duplicate of #31

**Closed by accumulator** 2021-08-28 07:29 UTC
